version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./init_scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql

  app:
    container_name: rest-api
    depends_on:
      - mysqldb
    build: ./.
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    volumes:
      - .m2:/root/.m2
volumes:
  db: