spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        globally_quoted_identifiers: true

    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: test_user
    password: GS3ef_fsd^!
    url: jdbc:mysql://localhost:3306/answer_king

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    username: test_user
    password: GS3ef_fsd^!
    url: jdbc:mysql://localhost:3306/answer_king_test

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    username: test_user
    password: GS3ef_fsd^!
    url: jdbc:mysql://mysqldb:3306/answer_king
