name: Terraform - EC2
on:
  workflow_run:
    workflows: ["Docker Image Pipeline"]
    branches:
      - main
      - master
      - develop
      - v1.1.0-preview.2
      - BENCH-280
    types:
      - completed

env:
  REGISTRY: ghcr.io/answerconsulting/answerking-java
  IMAGE_NAME: answer-king-rest-api_app #${{ github.repository }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    permissions:
      contents: read
      packages: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
      TF_ACTION_WORKING_DIR: 'terraform'

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false

      - name: Terraform format
        id: fmt
        run:  terraform fmt -check

      - name: Terraform Init
        id: init
        run:  terraform init

      - name: Terraform Validate
        id: validate
        run:  terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true
